name: Publish GitHub pages

on: workflow_dispatch

jobs:
  publish-ppa: # Use Github pages to publish the contents of ppa folder
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'master'
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'ppa'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
    